### ISSUE TITLE
MobileGestalt is Broken in iOS 17.4

### ISSUE THREAD

**Issue by Dantee296** [PoomSmart/MGKeys#8]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>MobileGestalt</key>
        <dict>
                <key>Status</key>
                <string>MobileGestaltDeprecated</string>
        </dict>
</dict>
</plist>


```

do we have any other source in replacement of MobileGestalt

**Comment by PoomSmart** [comment]
@Dantee296 Where do you get this plist from?

**Comment by Dantee296** [comment]
@PoomSmart its the response of idevicediagnostics mobilegestalt command when requested any key value

**Comment by jsonlee1688** [comment]
> @Dantee296 I see, but I don't see that this is the scope of MGKeys. When I add new keys, what I do are just:
> 
> 1. Extract `libMobileGestalt.dylib` from the dyld shared cache of an iOS device
> 2. Run `deobfuscate.sh` script to get the new unmapped obfuscated keys
> 3. Throw the dylib into Hopper or IDA to find the human-readable function that is referenced by each key
> 4. Verify that the function name converts to the obfuscated key it references to
> 5. Update the key mapping in `deobfuscated.py`
> 6. Run `deobfuscate.sh` again
> 
> This works regardless of that specific deprecation.

hey buddy, when will you update with iOS 17.4?

**Comment by PoomSmart** [comment]
It's out when it's out. Also there would be no updates anyway if the keys on iOS 17.4 are the same as what we have there now.

**Comment by jsonlee1688** [comment]
But it seems ios 17.4 can not get libMobileGestalt.dylib, the device coudnt get jailbreak. I was blocked at first step

**Comment by PoomSmart** [comment]
You can get the dylib by downloading the IPSW and extracting the dylib from the dyld_shared_cache which can be retrieved from the IPSW.

**Comment by jsonlee1688** [comment]
ok, i will have a try, thanks.
